// This file is generated by Firebase Extensions.
'use server';

/**
 * @fileOverview A flow for generating title and description copy suggestions for push notifications.
 *
 * - suggestNotificationCopy - A function that generates title and description copy suggestions for push notifications.
 * - SuggestNotificationCopyInput - The input type for the suggestNotificationCopy function.
 * - SuggestNotificationCopyOutput - The return type for the suggestNotificationCopy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestNotificationCopyInputSchema = z.object({
  topic: z.string().describe('The topic of the push notification.'),
  targetAudience: z
    .string()
    .describe('The target audience for the push notification.'),
  goal: z.string().describe('The goal of the push notification.'),
  brandVoice: z
    .string()
    .optional()
    .describe('The desired brand voice for the notification.'),
  currentTitle: z
    .string()
    .optional()
    .describe('The current title of the notification to be improved.'),
  currentMessage: z
    .string()
    .optional()
    .describe('The current message of the notification to be improved.'),
});

export type SuggestNotificationCopyInput = z.infer<
  typeof SuggestNotificationCopyInputSchema
>;

const SuggestNotificationCopyOutputSchema = z.object({
  titleSuggestions: z.array(z.string()).describe('Suggested titles.'),
  descriptionSuggestions: z
    .array(z.string())
    .describe('Suggested descriptions.'),
});

export type SuggestNotificationCopyOutput = z.infer<
  typeof SuggestNotificationCopyOutputSchema
>;

export async function suggestNotificationCopy(
  input: SuggestNotificationCopyInput
): Promise<SuggestNotificationCopyOutput> {
  return suggestNotificationCopyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestNotificationCopyPrompt',
  input: {schema: SuggestNotificationCopyInputSchema},
  output: {schema: SuggestNotificationCopyOutputSchema},
  prompt: `You are an expert copywriter specializing in push notifications.

{{#if currentTitle}}
  You will improve the following notification copy. If a brand voice is specified, you will rewrite the copy in that voice. If no brand voice is specified, you will just improve the copy.

  Current Title: {{{currentTitle}}}
  Current Message: {{{currentMessage}}}
{{else}}
  Generate compelling title and description copy suggestions for a push notification with the following characteristics:

  Topic: {{{topic}}}
  Target Audience: {{{targetAudience}}}
  Goal: {{{goal}}}
{{/if}}

Brand Voice: {{#if brandVoice}}{{{brandVoice}}}{{else}}Leave the brand voice neutral if not specified.{{/if}}

Provide three title suggestions and three description suggestions.

Format your response as a JSON object with the following schema:
{
  "titleSuggestions": ["title 1", "title 2", "title 3"],
  "descriptionSuggestions": ["description 1", "description 2", "description 3"]
}`,
});

const suggestNotificationCopyFlow = ai.defineFlow(
  {
    name: 'suggestNotificationCopyFlow',
    inputSchema: SuggestNotificationCopyInputSchema,
    outputSchema: SuggestNotificationCopyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
